business-sales-analytics/
│
├── README.md
├── data/
│   └── Sales_Data_MutasimAhmed.xlsx
├── dashboard/
│   ├── task_1.pbix
│   └── Dashboard_Screenshot.png
└── docs/
    └── DAX_Measures_PowerBI_MutasimAhmed.docx
